[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.21'
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = false
runs = 1000000
ffi = true
evm_version = "shanghai"

fs_permissions = [
    { access = "read-write", path = "./results" },
    { access = "read-write", path = ".temp_vyper_storage.json" },
]


remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "kernel/=lib/kernel/",
    "solady/=lib/solady/src/",
    "snekmate/=lib/snekmate/lib/",
    "vyper-storage/=lib/vyper-storage/src/",
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
